import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
import localFont from "next/font/local";
import  { Toaster } from "react-hot-toast";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const satoshi_regular = localFont({
  src: [{ path: "../public/fonts/Satoshi-Variable.ttf" }],
  variable: "--font-satoshi",
  display: "block",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${satoshi_regular.variable} font-sans`}>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased bg-[#f1f0ee]",
            fontSans.variable
          )}
        >
          <Toaster />

          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
